version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: dockerfile.dev
        ports:
            - '3001:3000'
        volumes:
            - ./src:/app/src
            - ./env:/app/env
        command: ['npm', 'run', 'start:dev']